export const accountData = [
  {
    accNo: 1234343,
    accBalance: 200,
    server: "OCTA-FX",
    leverage: "1:500",
    noSwap: "YES",
    fixedRate: "off",
    freeMargin: 0,
    equity: 0,
    isReal: true,
  },
  {
    accNo: 44444444,
    accBalance: 12,
    server: "OCTA-FX",
    leverage: "1:500",
    noSwap: "YES",
    fixedRate: "off",
    freeMargin: 2,
    equity: 90,
    isReal: false,
  },
  {
    accNo: 20000,
    accBalance: 400,
    server: "OCTA-FX",
    leverage: "1:500",
    noSwap: "YES",
    fixedRate: "off",
    freeMargin: 10,
    equity: 20,
    isReal: true,
  },
  {
    accNo: 2232334,
    accBalance: 200,
    server: "OCTA-FX",
    leverage: "1:500",
    noSwap: "YES",
    fixedRate: "off",
    freeMargin: 10,
    equity: 30,
    isReal: false,
  },
  // Add more dummy data with isReal property
  {
    accNo: 55555555,
    accBalance: 1000,
    server: "Demo-FX",
    leverage: "1:100",
    noSwap: "NO",
    fixedRate: "on",
    freeMargin: 50,
    equity: 200,
    isReal: false,
  },
  {
    accNo: 77777777,
    accBalance: 1500,
    server: "Live-FX",
    leverage: "1:1000",
    noSwap: "YES",
    fixedRate: "off",
    freeMargin: 100,
    equity: 800,
    isReal: true,
  },
];
