export const accountData = [
  {
    accNo: 1234343,
    accBalance: 200,
    server: "OCTA-FX",
    leverage: "1:500",
    noSwap: "YES",
    fixedRate: "off",
    freeMargin: 0,
    equity: 0,
  },
  {
    accNo: 44444444,
    accBalance: 12,
    server: "OCTA-FX",
    leverage: "1:500",
    noSwap: "YES",
    fixedRate: "off",
    freeMargin: 2,
    equity: 90,
  },
  {
    accNo: 20000,
    accBalance: 400,
    server: "OCTA-FX",
    leverage: "1:500",
    noSwap: "YES",
    fixedRate: "off",
    freeMargin: 10,
    equity: 20,
  },
  {
    accNo: 2232334,
    accBalance: 200,
    server: "OCTA-FX",
    leverage: "1:500",
    noSwap: "YES",
    fixedRate: "off",
    freeMargin: 10,
    equity: 30,
  },
];
