import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import NevBar from "./components/NevBar";
import Footer from "./components/Footer";
import Sidebar from "./components/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} flex bg-base-200`}>
        <div className="w-[80%] ">
          <NevBar />
          {children}
          <Footer />
        </div>
        <Sidebar />
      </body>
    </html>
  );
}
